docs/DevelopmentPlan/DevelopmentPlan.tex
Update to Kyles role to include ML/AI
=> Update to Roles

docs/DevelopmentPlan/DevelopmentPlan.tex
=> 7 dev plan reflection

docs/DevelopmentPlan/DevelopmentPlan.tex
Added Stakeholders - Shifting the code from my Word document to the tex file.
=> Added Stakeholders

docs/ProblemStatementAndGoals/ProblemStatement.tex
=> completed sections

docs/SRS/SRS.tex
=> Removed migration section

docs/SRS/SRS.tex
Content taken from Deliverable 1. If we get feedback on these parts before the deadline, an update can be made
=> Added Purpose of Project

docs/SRS/SRS.tex
With regards to the solution constraint, let me know if the browser one is a good one, or if it should be moved to be a requirement instead.
=> Added constraints to SRS

docs/SRS/SRS.tex
=> Added off the shelf solutions

docs/SRS/SRS.tex
=> added cultural reqs

docs/SRS/SRS.tex
=> Added maintenance reqs

docs/SRS/SRS.tex
No actual budget yet, just cost sources anticipation
=> Costs write up

docs/SRS/SRS.tex
=> New Problems writeup

docs/SRS/SRS.tex
closes #73 
Feel free to comment on any additional requirements missed here
=> 73 srs performance requirements

docs/SRS/SRS.tex
=> Added Legal Reqs

docs/SRS/SRS.tex
closes #70 
Please add additional functional reqs if any are omitted.
=> Updated Functional requirements

docs/SRS/SRS.tex
still need to add codeowners file. will do so after  complete SRS merge.
=> checking if code reviwers work

docs/SRS/SRS.tex
No clue what the expected format is for this.
=> Operational Requirements write up

docs/SRS/SRS.tex
=> Scope of the Work writeup

docs/HazardAnalysis/HazardAnalysis.tex
Note: references to security requirements will have to be updated
=> Failure Mode and Effect Analysis Table Added

docs/HazardAnalysis/HazardAnalysis.tex
References are ready as well, will push all together.
Added References.
=> Hazard Analysis Boundaries and Compoenents

docs/HazardAnalysis/HazardAnalysis.tex, docs/SRS/SRS.tex
Also added updates to SRS based on new Reqs.
@matpetro requested review since you made the table and i'd like to ensure you feel everything is covered.
=> Added Newly discovered requirements

docs/HazardAnalysis/HazardAnalysis.tex
I think the definition of hazard is important for marks so double check it makes sense
=> Added intro

docs/VnVPlan/VnVPlan.tex
=> Added NFR Tests for sections 13.5+

docs/VnVPlan/VnVPlan.tex
=> Added Introductory Paragraph and reference to SRS terms

docs/VnVPlan/VnVPlan.tex
Added Required Functional Requirements based on the SRS into the VnV.
=> Test for Functional Requirements

docs/VnVPlan/VnVPlan.tex
=> Added test traceability

docs/DevelopmentPlan/DevelopmentPlan.tex, docs/VnVPlan/VnVPlan.tex
closes #164 
Please check checklists closely, and add anything I missed
=> Completed Section 3

docs/VnVPlan/VnVPlan.tex
I missed FR test 10, meaning I had to shift stuff over. Here is how the tables look now:
=> Missed a FR test for VnV test Traceability

docs/VnVPlan/VnVPlan.tex
I will add the references to the SRS document in section 2.4 if the content here is fine.
=> Section 2 - VnV : Completed 

docs/projMngmnt/POC_Team_Contrib.tex
=> Added team metrics

docs/VnVPlan/VnVPlan.tex
Mentioned how percentages would be determined using survey results. Added question regarding error frustration
=> Mention of survey rank in tests

docs/VnVPlan/VnVPlan.tex
As suggested in peer review, linked to the site with valid QSAs and their details, mentioned a bit more about QSAs and mentioned the review would occur before public release.
=> Added QSA details

docs/HazardAnalysis/HazardAnalysis.tex
As suggested by a peer review, impact scores added. Did not add a probability column as probability was factored into the impact score
=> Added Impact Scores to Failure Modes

docs/Design/SoftArchitecture/MG.tex
All Interface and User Management Modules added to hierarchy and decomposed
=> MG Interface and User Management Modules

docs/Design/SoftDetailedDes/MIS.tex
=> MIS for interfaces and user management subsystem

docs/HazardAnalysis/HazardAnalysis.tex, docs/SRS/SRS.tex
closes #174 
If you can think of any additional things to add to glossary lmk and I can add them. Otherwise, lets try to add to it as we continue to edit other docs
=> Populated Glossary and added link

docs/HazardAnalysis/HazardAnalysis.tex
closes #156 
Just fixed the order of requirements and added clarifying sentence. Should not need much review
=> Improve clarity in section 6

docs/VnVPlan/VnVPlan.tex
All errors addressed
closes #243
=> VNV Format Errors

docs/Design/SoftArchitecture/MG.tex
Removed some anticipated changes I felt were too broad, redundant, or irrelevant.
closes #295
=> Anticipated Changes Module Links

docs/Design/SoftArchitecture/MG.tex
Added in modules for rest of requirements
closes #294
=> Finished Traceability

docs/VnVReport/VnVReport.tex
=> Traceability added

docs/VnVReport/VnVReport.tex
=> Changes made to Front end

docs/VnVReport/VnVReport.tex
=> Front end Unit test Overview

docs/SRS/SRS.tex
closes #118 
Updated requirement priorities as discussed in prior meeting
=> 118 peer review prioritization of requirements

docs/VnVReport/VnVReport.tex
=> Added automated testing summary

docs/ProblemStatementAndGoals/ProblemStatement.tex, docs/SRS/SRS.tex
=> Updated sections in SRS and PS for cross referencing

docs/VnVReport/VnVReport.tex
=> Added Functional Requirement Evaluation

docs/VnVPlan/VnVPlan.tex
=> Added link to VNVReport

docs/VnVReport/VnVReport.tex
4.3 Performance
4.7 Cultural
4.8 Compliance
4.9 User docs and training
=> Finished Section 4 

docs/VnVReport/VnVReport.tex
Reverts OKKM-insights/OKKM.insights#366
=> Revert "Finished Section 4 "

docs/VnVReport/VnVReport.tex
=> Finished section 7

docs/VnVReport/VnVReport.tex
=> Made formatting changes

docs/VnVReport/VnVReport.tex
=> Table captions added

docs/Design/SoftArchitecture/MG.tex, docs/Design/SoftDetailedDes/MIS.tex
=> 389 formatting

docs/VnVReport/VnVReport.tex
=> links added

docs/Design/SoftDetailedDes/MIS.tex
=> 390 design doc ta feedback   more mathematical specification

docs/HazardAnalysis/HazardAnalysis.tex
=> Fix typos, refs, naming consistency

docs/SRS/SRS.tex
=> Added likely changes section

docs/SRS/SRS.tex
=> Fix typos, formatting, and references

docs/VnVPlan/VnVPlan.tex
=> Added static testing and Confidence tests

docs/VnVPlan/VnVPlan.tex
closes https://github.com/OKKM-insights/OKKM.insights/issues/244
=> Added Responsibilties

docs/Design/SoftArchitecture/MG.tex
closes https://github.com/OKKM-insights/OKKM.insights/issues/296
Since Rev 0 is already done, there is no point of adding a new timeline. All other points in the Issue are fixed.
=> Timeline Link added + Caption and removed wrong reference of module.

docs/Design/SoftDetailedDes/MIS.tex
Closes https://github.com/OKKM-insights/OKKM.insights/issues/300
=> Data Type Clarity

docs/ProblemStatementAndGoals/ProblemStatement.tex, docs/ReflectAndTrace/ReflectAndTrace.tex
=> Final report
